MANUFACTURER_PRODUCT_TEMPLATE = {
    "manufacturer_name": "",
    "website": "",
    "product_name": "",
    "category": "",
    "description": "",
    "specs": {
        "size": "",
        "capacity": "",
        "weight": "",
        "material": "",
        "ingredients": "",
        "options": "",
        "package_type": "",
    },
    "features": [],
    "certifications": [],
    "oem_available": None,
    "odm_available": None,
    "target_use_case": [],
    "images": [],
    "source_urls": [],
    "extracted_keywords": [],
    "suitable_channels": [],
    "risks": [],
}

DISTRIBUTOR_PORTFOLIO_TEMPLATE = {
    "distributor_name": "",
    "website": "",
    "country": "",
    "locations": [],
    "warehouse_locations": [],
    "portfolio_categories": [],
    "handled_brands": [],
    "distribution_channels": [],
    "trade_types": {
        "import": None,
        "wholesale": None,
        "retail_distribution": None,
        "consignment": None,
        "exclusive_distribution": None,
    },
    "logistics_capability": "",
    "suitable_product_types": [],
    "weaknesses": [],
    "source_urls": [],
}

SELLER_PORTFOLIO_TREND_TEMPLATE = {
    "seller_name": "",
    "channels": [],
    "country": "",
    "portfolio_products": [],
    "best_sellers": [],
    "price_band": "",
    "categories": [],
    "content_style": [],
    "target_customer": [],
    "trend_keywords": [],
    "review_keywords": [],
    "social_metrics": {
        "followers": None,
        "posting_frequency": "",
        "engagement_level": "",
    },
    "commerce_capability": {
        "live_commerce": None,
        "content_creation": None,
        "paid_ads": None,
        "fulfillment": None,
    },
    "suitable_product_types": [],
    "source_urls": [],
}
