"""Standard Radar reporter for CommerceRadar.

Delegates to `flomers_kg.reporting` for the KG-based matching report. The
standard Radar interface (`generate_report`, `generate_index_html`) is
preserved here for orchestrator + tooling compatibility.
"""

from __future__ import annotations

from datetime import date
from pathlib import Path
from typing import Any


def _project_root() -> Path:
    return Path(__file__).resolve().parent.parent


def generate_report(
    *,
    project_root: Path | None = None,
    report_date: date | None = None,
) -> dict[str, Path]:
    """Generate the daily commerce report via the KG pipeline."""
    import sys

    root = project_root if project_root is not None else _project_root()
    src_path = root / "src"
    if str(src_path) not in sys.path:
        sys.path.insert(0, str(src_path))

    from flomers_kg.reporting import write_report_artifacts

    return write_report_artifacts(root, report_date=report_date)


def generate_index_html(
    *,
    project_root: Path | None = None,
) -> Path:
    """Return the path of the index.html generated by the report build."""
    paths = generate_report(project_root=project_root)
    return paths["index"]


__all__ = ["generate_report", "generate_index_html"]
